#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Summarize scenario-sweep batch reports.")
    p.add_argument(
        "--report-dir",
        type=Path,
        required=True,
        help="Folder with *_summary_*.json files generated by run_scenario_sweep.",
    )
    p.add_argument("--pattern", type=str, default="*_summary_*.json")
    return p.parse_args()


def main() -> int:
    args = parse_args()
    if not args.report_dir.exists():
        print(f"[error] report dir not found: {args.report_dir}")
        return 2

    files = sorted(args.report_dir.glob(args.pattern))
    if not files:
        print(f"[error] no summary files by pattern '{args.pattern}' in {args.report_dir}")
        return 3

    agg = defaultdict(lambda: {"n": 0, "score": 0.0, "lock_rate": 0.0, "fps": 0.0, "cont": 0.0})
    wins = Counter()

    for f in files:
        data = json.loads(f.read_text(encoding="utf-8"))
        rows = data.get("rows", [])
        if not rows:
            continue
        best = max(rows, key=lambda r: float(r.get("score", 0.0)))
        wins[str(best.get("preset", "unknown"))] += 1
        for r in rows:
            preset = str(r.get("preset", "unknown"))
            a = agg[preset]
            a["n"] += 1
            a["score"] += float(r.get("score", 0.0))
            a["lock_rate"] += float(r.get("lock_rate", 0.0))
            a["fps"] += float(r.get("avg_fps", 0.0))
            a["cont"] += float(r.get("continuity_score", 0.0))

    print(f"[info] summary files: {len(files)}")
    print("preset | runs | wins | avg_score | avg_lock_rate | avg_continuity | avg_fps")
    rows_out = []
    for preset, a in agg.items():
        n = max(1, int(a["n"]))
        row = {
            "preset": preset,
            "runs": int(a["n"]),
            "wins": int(wins.get(preset, 0)),
            "avg_score": a["score"] / n,
            "avg_lock_rate": a["lock_rate"] / n,
            "avg_continuity": a["cont"] / n,
            "avg_fps": a["fps"] / n,
        }
        rows_out.append(row)

    rows_out.sort(key=lambda r: (r["wins"], r["avg_score"]), reverse=True)
    for r in rows_out:
        print(
            f"{r['preset']} | {r['runs']} | {r['wins']} | "
            f"{r['avg_score']:.2f} | {r['avg_lock_rate']:.3f} | "
            f"{r['avg_continuity']:.3f} | {r['avg_fps']:.1f}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
